functionsDirectory = "D:\\Extra Storage\\MCP\\JJ_Tools\\04_DesignLab\\SparkStation\\website\\netlify\\functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
edge_functions = "D:\\Extra Storage\\MCP\\JJ_Tools\\04_DesignLab\\SparkStation\\website\\netlify\\edge-functions"
publish = "D:\\Extra Storage\\MCP\\JJ_Tools\\04_DesignLab\\SparkStation\\website\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "D:\\Extra Storage\\MCP\\JJ_Tools\\04_DesignLab\\SparkStation\\website\\netlify\\functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[edge_functions]]
path = "/go"
function = "go"

[[edge_functions]]
path = "/go/*"
function = "go"

[[edge_functions]]
path = "/s/*"
function = "go"

[dev]
command = "npm run dev"
port = 8888

[functions]

  [functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]